### ISSUE TITLE
missing config/secrets.yml

### ISSUE THREAD

**Issue by jnoconor** [learn-co-students/rails-url-helpers-lab-v-000#22]
A student forked the lab and ran the tests and got this error:

```
Failure/Error: visit students_path
     RuntimeError:
       Missing `secret_token` and `secret_key_base` for 'test' environment, set these values in `config/secrets.yml`
     # ./spec/features/student_spec.rb:6:in `block (2 levels) in <top (required)>'
```

Another student had the same problem and had copied the config/secrets.yml file from the previous lab to resolve the issue.

**Comment by bhollan** [comment]
I just did this lab and had no such problem.  It looks like the commit from @vicfriedman on Feb 18 fixed this issue.

**Comment by gj** [comment]
as @bhollan said, this was fixed here: https://github.com/learn-co-students/rails-url-helpers-lab-v-000/commit/ebe8190048a97548dd90167e7e66de2b025d7e2b

cc: @pletcher

**Comment by bhollan** [comment]
Touched this lab again today.  I think this issue is ready to be closed.
CC: @aturkewi
