### ISSUE TITLE
.active method doesn't work even when set up properly and needs a funky fix...

### ISSUE THREAD

**Issue by febbraiod** [learn-co-students/rails-url-helpers-lab-v-000#23]
<img width="653" alt="screen shot 2016-02-13 at 2 23 07 pm" src="https://cloud.githubusercontent.com/assets/15745614/13029576/0d195490-d25e-11e5-9ad3-52f762632b3c.png">

**Comment by AdamKing0126** [comment]
You could set it when you add the column in your migration:
`add_column :students, :active, :boolean, default: false`

**Comment by febbraiod** [comment]
yeah I did that, still didn't work. I think it's in my first commit for this lab

**Comment by morgvanny** [comment]
you aren't setting the @student properly in your student controller in the show method. you call .active on it before setting it to anything. if you call set_student first there, that should solve your problem
